### ISSUE TITLE
Templated components and Razor Templates

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor.Docs#251]
Add content on templated components:
- `RenderFragment<T>`, Razor templates
- Generic components
- Type inference
- Context parameter

https://github.com/aspnet/Blazor/pull/1360
https://github.com/aspnet/Blazor/pull/1404
https://github.com/aspnet/Blazor/pull/1417
https://github.com/aspnet/Blazor/pull/1453
https://github.com/aspnet/Blazor/pull/1470

**Comment by danroth27** [comment]
Yeah, that would be great.

**Comment by guardrex** [comment]
@danroth27 Questions ...

1. I can't see milestones for the scenario PRs because they don't seem to have associated issues in the Blazor repo. These are for 0.6.0, right? Since 0.6.0 isn't released, we're aiming to publish coverage for both scenarios immediately after 0.6.0 comes out, correct? If so, I'd put this on my schedule for the Sunday immediately following release or the day of/after if you want me to slide it in mid-week.
1. These scenarios are on the same issue here. Are generic-typed components ...
   a. A section of the existing Components topic?
   b. It's own topic? Our "Components" topic is a landing page on a TOC node "Components," so we can roll a new standalone topic under that node if you want. That was my plan for components scenarios ... any of the current sections of the Components topic can be split out at any time into its own topic under this node.
   c. Covered with templates? ... a templates example has a generic-typed component, and that's the only place a generic-typed component appears.
1. Place the templates topic under the Components node or in the main TOC? If main TOC, where along the list in the nav sidebar should it appear?

If there's a split in scenario coverage (2a or 2b), I'd like to open these scenarios on separate doc issues. I would seek to get them both covered on the same day; but if I fail, we could at least get one merged quickly and the other would follow shortly thereafter.

**Comment by danroth27** [comment]
Hi @guardrex,

Yes, all of the templated component work is in 0.6.0. Everything planned for 0.6.0 is pretty much wrapped up. We plan to do some validation on the 0.6.0 bits and then push out the 0.6.0 release either later this week or early next week.

I would cover all of this (generic typed components, component templates) as sections in the components topic. If you think the components topic is getting too big and unweildy, I'm open to splitting it out into separate subtopics.

We should also cover type inference for generic typed components: https://github.com/aspnet/Blazor/pull/1453

**Comment by guardrex** [comment]
@danroth27 Perfect. I'll get bored after a few days of PTO this week anyway. :smile:

> sections in the components topic

If either of these sections turn out too *BIG* (Ryan's issue remarks on Templated Components are fairly 🍖 *meaty*), then we can split out one or both into a topic on review.

I haven't been building for pre-releases. My pattern has been to use RTM bits and crank the doc work out quickly (e.g., sample updates). Since I'll be on "vacation," I should be able to do the work same day as the release.
