### ISSUE TITLE
Getting started with Blazor - documentation incorrect

### ISSUE THREAD

**Issue by Noobville** [aspnet/Blazor.Docs#382]
url: 
https://blazor.net/docs/get-started.html
Following instructions 1 - 4.
1 - ok , 2 ok (though I did in reverse order)
3 (Blazor languages Services extension) is a link to another page, which mirrors original get started page.
4 - dotnet new install templates - nuget error: NU1101 Unable to find package ...Blazor.Templates ( in offline packages) 

Link in 3 is : https://marketplace.visualstudio.com/items?itemName=aspnet.blazor
This has the same 4 steps above. Step 3 is a link to itself.

My failure in 4 - Partially resolved by setting nuget source from within 2017. However, failured to install again (404 not found, retrying)

**Comment by tomcavanaugh** [comment]
On initial attempt to follow these steps, received the error: 
Assets file project.assets.json not found. Run a NuGet package restore

Had to run the command "dotnet restore" from the Package Manager Console to resolve.

**Comment by danroth27** [comment]
@Noobville The link to the VS marketplace is correct for downloading the Blazor Language Service Extension. Just click the big green download button on that page to get the extension.

I'm not sure why you got a package restore failure, but I'm guessing it's due to an issue with your network or your nuget configuration.

@tomcavanaugh You shouldn't need to run dotnet restore after create the template. That might be a .NET Core SDK bug (https://github.com/dotnet/core-sdk).
